### ISSUE TITLE
Dependencies not installed with 'pip install'

### ISSUE THREAD

**Issue by jbweston** [qucat/qucat#37]
Steps to reproduce:

```
conda create -n qucat
conda activate qucat
pip install qucat
python -c 'import qucat'
```
This produces the following traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jbw/.local/miniconda/lib/python3.7/site-packages/qucat/__init__.py", line 2, in <module>
    from .core import *
  File "/home/jbw/.local/miniconda/lib/python3.7/site-packages/qucat/core.py", line 1, in <module>
    import sympy as sp
ModuleNotFoundError: No module named 'sympy'
```

This can be easily fixed by specifying `install_requires` in `setup.py`

**Comment by mgely** [comment]
Fixed in 74f477cadd0b531587b0581c9628e43525f57f84
